### ISSUE TITLE
Issue loading the Birch Hedgehog Feature with loading new chunks

### ISSUE THREAD

**Issue by warrenonedge** [0rc1nus/Hedgehog-Main#2]
https://pastebin.com/R1WcYwHj

Using the Better Minecraft (Forge 1.18.1) v15 mod which uses hedgehog v1.1.0 seems to crash when loading chunks that spawn the Hedgehog birch tree feature. Removing the mod fixes the crash issue.

**Comment by warrenonedge** [comment]
may be fixed in 1.1.1?

**Comment by 0rc1nus** [comment]
This issue was fixed in hedgehog v1.1.1+
